version: '3.9'
services:
  nginx:
    image: nginx
    user: root
    ports:
      - "8080:80"
    links:
      - miniserver:2.0
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - /var/lib/nginx/body

  miniserver:
    build:
      context: ./05
    ports:
      - "80:81"
