version: '3.9'

services:
  nginx_proxy:
    build: ./server/
    ports: 
    - "80:8080"
    networks:
      - my-net
    depends_on:
    - miniserver



  miniserver:
    image: miniserver_hallow:1.0
    user: root
    build: ./05/
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
