name: CI_CD for DO5_Simple_docker Project

on:
  push: 
    branches: [ "test_actions" ]
    

jobs:
  test:
    runs-on: ubuntu-latest


      steps:
       - name: Checkout code
          uses: actions/checkout@v4

       - name: Echo_simple
          run: echo Hello, world


