
on:
  push:
    branches: [ "DO5_Part_01" ]

jobs:
  test_part_01:
    runs-on: on_VM_hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker_pull
        run: docker pull nginx

      - name: Docker_images
        run: docker images

      - name: Start_docker_image_nginx
        run: docker run -d nginx

      - name: Docker_inspect_and_stop
        run: |
          output=$(docker ps -q)
          docker inspect $output
          docker stop $output
          if docker ps -q | grep $output; then
            echo "Container in use. Exiting with error."
            exit 1
          else
            echo "OK"
          fi

      - name: Check if port 80 is in use
        run: |
          if fuser -k 80/tcp; then
            echo "Port 80 is in use. Exiting with error."
            exit 1
          else
            echo "Port 80 is not in use."
          fi

      - name: Docker_with_ports  
        run: | 
          docker run -d -p 80:80 -p 443:443 nginx
         # docker ps -q 

      - name: Postman_test
        working-directory: DO5_SimpleDocker-1-develop/src/01/
        run: newman run postman_test.json

  test_part_02:
    runs-on: on_VM_hosted
      
    steps:
      - uses: actions/checkout@v4

      - name: Docker exec
        run: |
          output=$(docker ps -q)
          docker exec -it $output cat /etc/nginx/nginx.conf
