on:
  push:
    branches: [ "DO5_Part_06" ]

jobs:
  test_:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g newman
         
      - name: Install Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

     
      - name: Docker_images
        run: docker images

      - name: Compose
        run: |
          cd DO5_SimpleDocker-1-develop/src/06/
          docker-compose build
          docker-compose up -d

      - name: Docker_images_after_compose
        run: |
          docker images
          docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Ports}}'

          
      - name: Postman_test_of_status_page
        run: |
          cd DO5_SimpleDocker-1-develop/src/06/
          newman run postman_test_Part_06.json 
