name: "CI_CD for DO5_Simple_docker Project"

on:
  push:
    branches: [ "DO5_Part_01" ]

jobs:
  test:
    runs-on: on_VM_hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker_pull
        run: docker pull nginx

      - name: Docker_images
        run: docker images

      - name: Start_docker_image_nginx
        run: docker run -d nginx

      - name: Docker_inspect
        run: |
          output=$(docker ps | sed -n '2p' | awk '{print $1}')
          echo "$output" >> $GITHUB_ENV
          docker inspect ${{ env.output }}

      - name: Postman_test
        working-directory: DO5_SimpleDocker-1-develop/src/01/
        run: newman run postman_test.json
