name: "CI_CD for DevOps7 project"

on:
  push: 
    branches: [ "DevOps_7_Part_03" ]

jobs:
  test_:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g newman
         
      - name: Install Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

     
      - name: Docker_images
        run: docker images

      - name: Compose
        run: |
          cd DevOps_7-1/src/Part_3
          docker-compose build
          docker-compose up -d

      - name: Docker_images_after_compose
        run: |
          docker images
          docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Ports}}'

      - name: Pause for 60 seconds
        run: sleep 60

      - name: Network_and_ports_information
        run: |
          docker network ls
          docker container port Part_3_session-service_1
          docker container port Part_3_gateway-service_1
          
                    
      - name: Postman_test
        working-directory: DevOps_7-1/src/
        run: newman run application_tests.postman_collection.json


