name: "CI_CD for DO5_Simple_docker Project"

on:
  push: 
    branches: [ "test_actions" ]
    
    
jobs:
  test:
    runs-on: [ on_VM_hosted ]
 

    steps:
      - uses: actions/checkout@v4

      - name: Echo_simple
        run: |
          echo "Hello, world"
          pwd

      - name: Install FastCGI
        run: |
          pwd

          
          sudo apt-get update
          sudo apt-get install -y libfcgi-dev build-essential
          sudo apt install spawn-fcgi
      
      - name: Install and start NGINX
        working-directory: DO5_SimpleDocker-1-develop/src/03/
        run: |
           pwd
           
           sudo cp nginx.conf /etc/nginx/nginx.conf
           sudo systemctl restart nginx
      #    sudo systemctl enable nginx
      #    sudo systemctl start nginx
      #    sudo systemctl status nginx


      - name: Build
        working-directory: DO5_SimpleDocker-1-develop/src/03/
        run: |

          gcc -o miniserver miniserver.c -lfcgi
          spawn-fcgi -v
          spawn-fcgi -p 8080 -n ./miniserver &
          sleep 5
          curl -f http://localhost:81


