name: "CI_CD for DO5_Simple_docker Project"

on:
  push: 
    branches: [ "test_actions" ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo_simple
        run: |
          echo "Hello, world"
          pwd

      - name: Install FastCGI
        run: |
          sudo apt-get update
          sudo apt-get install -y libfcgi-dev build-essential
        


