name: "CI_CD for DO5_Simple_docker Project"

on:
  push: 
    branches: [ "test_actions" ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Echo_simple
        run: |
          echo "Hello, world"
          pwd

      - name: Install FastCGI
        run: |
          sudo apt-get update
          sudo apt-get install -y libfcgi-dev build-essential
          sudo apt install spawn-fcgi

      - name: Build
        run: |
          cd DO5_SimpleDocker-1-develop/src/04/
          gcc -o miniserver miniserver.c -lfcgi
          ls -l
          spawn-fcgi -v
          spawn-fcgi -p 8080 -n ./miniserver
          curl http://localhost/8080

