on:
  push:
    branches: [ "DO5_Part_04" ]

jobs:
  test_:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g newman

      - name: Create and Run Image
        working-directory: DO5_SimpleDocker-1-develop/src/04/
        run: |
          docker build -t miniserver:1.0 .
          docker run -dt -p 80:81 miniserver:1.0 
     
      - name: Docker_images
        run: docker images

      - name: Postman_test_of_main_page
        run: |
          cd DO5_SimpleDocker-1-develop/src/04/
          newman run Test_part_04.json --folder "Test_main_page"

      - name: Copy nginx configuration
      
        run: |
          pwd
          cd DO5_SimpleDocker-1-develop/src/04/
          docker cp nginx_status.conf $(docker ps -q):/etc/nginx/nginx.conf
          docker exec $(docker ps -q) nginx -s reload
          sleep 5

          
      - name: Postman_test_of_status_page
        run: |
          cd DO5_SimpleDocker-1-develop/src/04/
          newman run Test_part_04.json --folder "Test_status_page"

