name: "CI_CD for DO5_Simple_docker Project"

on:
  push: 
    branches: [ "DevOps_7_Part_01" ]

    
    
    
jobs:
  test:
    runs-on: self-hosted
 

    steps:
      - uses: actions/checkout@v4

      #- name: Echo_simple
      #  run: |
      #    echo "Hello, world"
      #    pwd

      #- name: Install FastCGI
      #  run: |
      #    pwd
      #    echo ${{ secrets.SUDO_PASSWORD }} | sudo -S apt-get update
      #    echo ${{ secrets.SUDO_PASSWORD }} | sudo -S apt-get install -y libfcgi-dev build-essential
      #    echo ${{ secrets.SUDO_PASSWORD }} | sudo -S apt install spawn-fcgi

      
     # - name: restart NGINX
     #   working-directory: DO5_SimpleDocker-1-develop/src/03/
     #   run: |
     #      pwd
     #      echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/nopasswd
           
     #      sudo cp nginx.conf /etc/nginx/nginx.conf
     #      sudo systemctl restart nginx
      #    sudo systemctl enable nginx
      #    sudo systemctl start nginx
      #    sudo systemctl status nginx


     # - name: Build
     #   working-directory: DO5_SimpleDocker-1-develop/src/03/
     #   run: |

     #     gcc -o miniserver miniserver.c -lfcgi
     #     spawn-fcgi -v
     #     spawn-fcgi -p 8080 -n ./miniserver &
     #     sleep 5
      - name: Postman_test
        working-directory: DevOps_7/src/
        run: newman run application_tests.postman_collection.json


